# Generated by Django 3.2 on 2023-06-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YuMetrics_app', '0002_auto_20230617_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='transcript',
            field=models.CharField(max_length=50, verbose_name='Metric name transcript'),
        ),
    ]
